spring:
  devtools:
    remote:
      secret: 'D&vo&&iFBkKPD5IqwU7,ix{#iC7qC1RrE3y$6dip;GI}sBr9[Aw"52E9M@v!<(4'

  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mercado-db:3306/mercado-db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: ifljava