CREATE TABLE mercado (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    cnpj VARCHAR(14) NOT NULL,
    nome VARCHAR(40) NOT NULL,
    is_ativo BOOLEAN DEFAULT 1 NOT NULL,
    data_inclusao DATETIME NOT NULL,
    data_atualizacao DATETIME DEFAULT NULL,
    PRIMARY KEY (id)
);